# .goreleaser.yaml
version: 2
project_name: k10s

before:
  hooks:
    - go mod tidy

builds:
  - id: k10s
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64

    binary: k10s

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: benly50s
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula
    homepage: "https://github.com/benly50s/k10s"
    description: "Benly's Kubernetes Cluster Manager with TUI"
    license: "MIT"
    
    dependencies:
      - name: kubernetes-cli
        type: optional
      - name: k9s
        type: optional
      - name: kubelogin
        type: optional
      - name: argocd
        type: optional

    install: |
      bin.install "k10s"
      bash_completion.install "completions/k10s.bash" => "k10s"
      zsh_completion.install "completions/k10s.zsh" => "_k10s"
      fish_completion.install "completions/k10s.fish"

    test: |
      system "#{bin}/k10s --help"
